name: CI
permissions:
  contents: read
  pull-requests: write
  checks: write

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'master:schema.graphql'
          annotations: true
