name: Check GraphQL Schema

on:
  - push

jobs:
  test:
    name: Check GraphQL Schema
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      checks: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: br24-cms/schema.graphql # important to define a path to schema file, without a branch
          endpoint: 'https://pikud-haoref-graphql-api.tuval-simha.workers.dev/graphql'
          annotations: true
          fail-on-breaking: false
